name: "Getting Started 2 Github Actions"
run-name: "Getting Started 2 with ${{ github.actor }}"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@master

      - name: "My Custom action Test"
        uses: ./my-custom-action/
        with:
          name: "Quadri"
    
