name: "Getting Started 2 Github Actions"
run-name: "Getting Started 2 with ${{ github.actor }}"
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@master

      - name: "My Custom action Test"
        uses: ./my-custom-action
        with:
          name: "Quadri"
          
      - name: workflow commands logging messages
        run: |
          echo "::debug::This is a debug message"
          echo "This is an info message"
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"
    
